### ISSUE TITLE
Add capture of user entered information and search result selections

### ISSUE THREAD

**Issue by gleonard-m** [mozilla/mlhackweek2021#1]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

_1) What questions will you answer with this data?_
Data collection is for a Data Org Hack Week event.  The data is needed to train a ranking model for Hack Week and will not be used externally.

_2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:_
This data will be used during a Data Org Hack Week event.

_3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_
Mozilla currently does not have this data available for use.

_4) Can current instrumentation answer these questions?_
Mozilla currently does not have this data available for use.

_5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki._   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

See https://github.com/mozilla/mlhackweek2021/blob/588d809f22cef9ce6c5b2a13c3d5a9680ed37c9f/searchapp/mysite/searchranking/glean_config/metrics.yaml

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Search engine used</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td>https://github.com/mozilla/mlhackweek2021/issues/1</td>
  </tr>
  <tr>
    <td>Submitted search text  </td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
  <tr>
    <td>Web session id</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
  <tr>
    <td>Selected search result url </td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
  <tr>
    <td>Selected search result hostname (domain) </td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
  <tr>
    <td>Selected search result title</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Selected search result short description</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Selected search result starting text    </td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Selected search result position         </td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Url select state           </td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Timestamp of selection action</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Unselected search result url</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Unselected search result hostname (domain)</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Unselected search result title</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Unselected search result short description</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Unselected search result starting text</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
<tr>
    <td>Unselected search result position</td>
    <td>Category 3 “Stored Content & Communications”</td>
    <td></td>
  </tr>
</table>

_6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way._
This data is will not be publicly available.

_7) How long will this data be collected?  Choose one of the following:_
This is scoped to a time-limited experiment/project until date 12-31-2021.

_8) What populations will you measure?_
Data will only be collected from Mozilla employees with consent (all release channels and locales).

_9) If this data collection is default on, what is the opt-out mechanism for users?_
The data collection will be performed using a web application, not Firefox.  Users have an option to not use the application thus not preventing their data from being collected.

_10) Please provide a general description of how you will analyze this data._
The data will be used as a machine learning data set for a Data Org Hack Week event.

_11) Where do you intend to share the results of your analysis?_
The results will be shared within Mozilla only.

_12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:_
No

**Comment by travis79** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
> _1) What questions will you answer with this data?_
> Data collection is for a Data Org Hack Week event. The data is needed to train a ranking model for Hack Week and will not be used externally.
> 
> _2) Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:_
> This data will be used during a Data Org Hack Week event.
> 
> _3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_
> Mozilla currently does not have this data available for use.
> 
> _4) Can current instrumentation answer these questions?_
> Mozilla currently does not have this data available for use.
> 
> _5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki._
> 
> **Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**
> 
> See [`588d809`/searchapp/mysite/searchranking/glean_config/metrics.yaml](https://github.com/mozilla/mlhackweek2021/blob/588d809f22cef9ce6c5b2a13c3d5a9680ed37c9f/searchapp/mysite/searchranking/glean_config/metrics.yaml)
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Search engine used 	Category 3 “Stored Content & Communications” 	https://github.com/[/issues/1](https://github.com/mozilla/mlhackweek2021/issues/1)
> Submitted search text 	Category 3 “Stored Content & Communications” 	
> Web session id 	Category 3 “Stored Content & Communications” 	
> Selected search result url 	Category 3 “Stored Content & Communications” 	
> Selected search result hostname (domain) 	Category 3 “Stored Content & Communications” 	
> Selected search result title 	Category 3 “Stored Content & Communications” 	
> Selected search result short description 	Category 3 “Stored Content & Communications” 	
> Selected search result starting text 	Category 3 “Stored Content & Communications” 	
> Selected search result position 	Category 3 “Stored Content & Communications” 	
> Url select state 	Category 3 “Stored Content & Communications” 	
> Timestamp of selection action 	Category 3 “Stored Content & Communications” 	
> Unselected search result url 	Category 3 “Stored Content & Communications” 	
> Unselected search result hostname (domain) 	Category 3 “Stored Content & Communications” 	
> Unselected search result title 	Category 3 “Stored Content & Communications” 	
> Unselected search result short description 	Category 3 “Stored Content & Communications” 	
> Unselected search result starting text 	Category 3 “Stored Content & Communications” 	
> Unselected search result position 	Category 3 “Stored Content & Communications” 	
> 
> _6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way._
> This data is will not be publicly available.
> 
> _7) How long will this data be collected? Choose one of the following:_
> This is scoped to a time-limited experiment/project until date 12-31-2021.
> 
> _8) What populations will you measure?_
> Data will only be collected from Mozilla employees with consent (all release channels and locales).
> 
> _9) If this data collection is default on, what is the opt-out mechanism for users?_
> The data collection will be performed using a web application, not Firefox. Users have an option to not use the application thus not preventing their data from being collected.
> 
> _10) Please provide a general description of how you will analyze this data._
> The data will be used as a machine learning data set for a Data Org Hack Week event.
> 
> _11) Where do you intend to share the results of your analysis?_
> The results will be shared within Mozilla only.
> 
> _12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:_
> No

# Data Review 

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, the user can opt-out of collection by simply not running the app while browsing.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, the program/project is set to end collection on 2021-12-31

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 3, Stored content and communications

5) Is the data collection request for default-on or default-off?

Default-off, the user must install and use the application while using the browser for collection to occur.

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Comment by travis79** [comment]
cc @nshadowen for visibility
